# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EggWarriors' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftLint'

  # Pods for EggWarriors

  target 'EggWarriorsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EggWarriorsUITests' do
    # Pods for testing
  end

end
